# Generated by Django 5.0.6 on 2024-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='client_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
